### ISSUE TITLE
feature request: add alpine as base image

### ISSUE THREAD

**Issue by H01001000** [LukeChannings/docker-deno#5]
To reduce the size of the image, ~20MB save based on the official deno image, I hope we can also build one more version of the image with alpine

**Comment by LukeChannings** [comment]
For an alpine image to work I'd need to compile the binary against musl instead of glibc, which [might](https://andygrove.io/2020/05/why-musl-extremely-slow/) [make](https://pythonspeed.com/articles/alpine-docker-python/) deno unnecessarily slower.

Considering the fact that overlayfs caches the base image, and Ubuntu is a commonplace base, you're not really saving the 20MB, and even if you were, 20MB is not enough of a saving to compel me to spend time on this. My apologies.
